# Generated by Django 3.1.6 on 2021-02-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuego.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
